### ISSUE TITLE
Smart contract languages

### ISSUE THREAD

**Issue by andrewfowl** [Encode-Club-Solidity-Foundations/Lesson-02#11]
Are there any smart contract frameworks that are more efficient for certain purposes than solidity?

**Comment by MatheusDaros** [comment]
Hello @andrewfowl 
It really depends a lot on what you are trying to do.
It is very common to use libraries like OpenZeppelin to compose your contracts, especially around using tokens. But the whole philosophy of Solidity is to keep things simple and composable. This is why using big chunks of frameworks and base material very often can cause more harm than actually improve on efficiency or security.
