### ISSUE TITLE
Free functions without visibility modifiers - any reason to use them?

### ISSUE THREAD

**Issue by conors-code** [Encode-Club-Solidity-Foundations/Lesson-02#13]
Hi Matheus,
I was playing around with contracts during the week and got the error "free functions cannot have visibility".  
It turned out that I had unwittingly already ended the contract about with a closign bracket }
Thinking about it. does that error mean that in solidity you can viably have functions existing outside of contracts / libraries / interfaces, so long as they don't have a visibility assigned?  If so, what use-cases would be best filled by such free functions?
Thanks,
Conor

**Comment by MatheusDaros** [comment]
Hello @conors-code 
Thanks for the question.
It is great to see that we're experimenting and discovering from the error messages.

As we can see in the documentation:
> A free function behaves like an internal function of the contract that called it. The main difference is that a free function cannot directly access state variables and internal functions of contracts

So you can indeed create functions outside contracts, and call them inside other objects. The only thing is that it will lack some capabilities, as explained above.

**Comment by conors-code** [comment]
Thanks Matheus, that makes sense.
