### ISSUE TITLE
Error while deploying IhelloWorld

### ISSUE THREAD

**Issue by Yash-Gadhade** [Encode-Club-Solidity-Foundations/Lesson-02#6]
![image](https://user-images.githubusercontent.com/54960948/193994241-216b4639-9f90-485a-9f3d-219cc6d62be4.png)

Getting this as an error while deploying IHelloWorld
This is code
`// SPDX-License-Identifier: MIT

pragma solidity >=0.7.0 <0.9.0;

interface IHelloWorld {
    function helloWorld() external view returns (string memory);
    function setText(string memory newText) external ;    
} 

contract HelloWorld is IHelloWorld{
    string internal text;

    function helloWorld() public view override returns (string memory) {

    }
    function setText(string memory newText) public override  {
        text= newText;
    }
}`

Please help me resolve it

**Comment by MatheusDaros** [comment]
It seems that you are trying to deploy the `HelloWorld` contract, but you have selected the `IHelloWorld` at the dropdown

**Comment by Yash-Gadhade** [comment]
> 

Yes, I want to deploy IHelloWorld, but for some reason, I cannot deploy it due to the error showcased.

**Comment by MatheusDaros** [comment]
But `IHelloWorld` is an interface. Are you indeed trying to deploy an interface?
Interfaces don't have any implementations on itself.

**Comment by Yash-Gadhade** [comment]
Okay, I got it. Thank you, Matheus!
