### ISSUE TITLE
ABI and Bytecode

### ISSUE THREAD

**Issue by HoloNine** [Encode-Club-Solidity-Foundations/Lesson-02#7]
Hi @MatheusDaros ,

I was playing arround with the remix ide, trying to understand it's functionality, and in the solidity compiler tab there are two small buttons at the very bottom called "ABI" and "Bytecode". If i'm right the bytecode is the data representation of the smart contract as opcode, but I don't realy understand the ABI. It's some kind of interpreter between solidity code and opcode?

Thank you

**Comment by MatheusDaros** [comment]
Hello @wisethee 
Thanks for your question.

ABIs are compiled artifacts as well, just like the Bytecode, but with the purpose of guiding/helping contract interactions.

> The Contract Application Binary Interface (ABI) is the standard way to interact with contracts in the Ethereum ecosystem, both from outside the blockchain and for contract-to-contract interaction. Data is encoded according to its type, as described in this specification. The encoding is not self describing and thus requires a schema in order to decode.

Read more about it in the [Solidity docs](https://docs.soliditylang.org/en/latest/abi-spec.html)
